name: Build and Deploy Documentation

# 讓 GITHUB_TOKEN 擁有 push gh-pages 所需的權限
permissions:
  contents: write   # 允許寫程式碼與 git push
  pages:   write   # 允許操作 GitHub Pages
  id-token: write  # 有些 action 需要用到

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # （也可把 permissions 放在這裡，效果一樣）
    # permissions:
    #   contents: write
    #   pages:   write
    #   id-token: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      run: |
        # … 你的 Sphinx/國際化指令 …

    - name: Create .nojekyll file
      run: |
        cd docs/build/html
        touch .nojekyll
        echo '<meta http-equiv="refresh" content="0; url=./zh_TW/index.html">' > index.html

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: docs/build/html
        # token 參數預設就是 GITHUB_TOKEN，通常可不寫
        # token: ${{ secrets.GITHUB_TOKEN }}
