# .github/workflows/docs.yml

name: 部署文檔到GitHub Pages

on:
  push:
    branches:
      - main  # 設置哪些分支的推送會觸發文檔部署
    paths:
      - 'docs/**'  # 只有文檔目錄變更時才觸發
      - 'pretty_loguru/**'  # 或源碼變更時也觸發
  # 允許手動觸發工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出儲存庫
        uses: actions/checkout@v3

      - name: 設置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝依賴
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints myst-parser

      - name: 構建文檔
        run: |
          cd docs
          make clean
          make html

      - name: 部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          force_orphan: true
          commit_message: "部署文檔: ${{ github.event.head_commit.message }}"