name: Build and Deploy Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints myst-parser sphinx-intl
        pip install -e .
    
    - name: Build Default docs
      run: |
        cd docs
        # 確認 Makefile 位置並查看其內容
        ls -la
        if [ -f "Makefile" ]; then
          make html
        else
          # 如果沒有 Makefile，直接使用 sphinx-build
          sphinx-build -b html source build/html
        fi

    - name: Build Chinese docs
      run: |
        cd docs
        sphinx-build -b gettext source build/gettext
        sphinx-intl update -p build/gettext -l zh_TW
        sphinx-intl build
        sphinx-build -b html -D language=zh_TW source build/html/zh_TW
    
    - name: Build English docs
      run: |
        cd docs
        sphinx-build -b gettext source build/gettext
        sphinx-intl update -p build/gettext -l en
        sphinx-intl build
        sphinx-build -b html -D language=en source build/html/en
    
    - name: Create .nojekyll file
      run: |
        cd docs/build/html
        touch .nojekyll
        # 創建根目錄重定向檔案
        echo '<meta http-equiv="refresh" content="0; url=./zh_TW/index.html">' > index.html
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: docs/build/html